apiVersion: v1
kind: Service
metadata: {name: app-service, namespace: novacloud-app}
spec:
  selector: {app: app-service}
  ports: [{port: 8080, targetPort: 8080}]
---
apiVersion: apps/v1
kind: Deployment
metadata: {name: app-service, namespace: novacloud-app}
spec:
  replicas: 1
  strategy: {type: Recreate}
  selector:
    matchLabels: {app: app-service}
  template:
    metadata:
      labels: {app: app-service, app.kubernetes.io/part-of: novacloud}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: app-service
          image: novacloud-lab/app-service:0.1.0
          imagePullPolicy: IfNotPresent
          ports: [{containerPort: 8080}]
          envFrom:
            - configMapRef: {name: java-config}
          env:
            - name: PLATFORM_GATEWAY_URL
              value: http://platform-gateway.novacloud-platform.svc.cluster.local:8080
          resources:
            requests: {cpu: 100m, memory: 256Mi}
            limits: {memory: 768Mi}
          startupProbe:
            httpGet: {path: /actuator/health, port: 8080}
            periodSeconds: 5
            timeoutSeconds: 4
            failureThreshold: 60
          readinessProbe:
            httpGet: {path: /actuator/health, port: 8080}
            periodSeconds: 5
            timeoutSeconds: 4
