apiVersion: v1
kind: Namespace
metadata:
  name: novacloud-app
  labels: {app.kubernetes.io/part-of: novacloud}
---
apiVersion: v1
kind: Namespace
metadata:
  name: novacloud-platform
  labels: {app.kubernetes.io/part-of: novacloud}
---
apiVersion: v1
kind: Namespace
metadata:
  name: novacloud-infra
  labels: {app.kubernetes.io/part-of: novacloud}
