server:
  port: 8080
spring:
  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}
      connect-timeout: 2s
      timeout: 2s
  application:
    name: platform-gateway
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:nacos:8848}
        namespace: platform
        group: DEFAULT_GROUP
management:
  endpoints:
    web:
      exposure:
        include: health
spring.cloud.gateway:
  httpclient:
    connect-timeout: 2000
    response-timeout: 8s
  routes:
    - id: platform-service
      uri: lb://platform-service
      predicates:
        - Path=/api/tickets/**,/api/auth/**
      filters:
        - AddResponseHeader=X-Lab-Platform-Gateway, visited

